language: objective-c
osx_image: xcode9.4
xcode_workspace: Apollo.xcworkspace

matrix:
  include:
  - xcode_scheme: Apollo
    xcode_sdk: iphonesimulator11.4
    env: DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone 8"

script:
  - set -o pipefail
  - xcodebuild clean build build-for-testing -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
  - xcodebuild test-without-building -workspace "${TRAVIS_XCODE_WORKSPACE}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
